"""Terraform File Structure Builder.

Generiert Terraform-Datei-Struktur (main.tf, variables.tf, outputs.tf).
"""

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class TerraformProject:
    """Repräsentiert ein generiertes Terraform-Projekt."""

    # File Contents (filename → content)
    files: dict[str, str] = field(default_factory=dict)

    # Metadata
    provider: str = "aws"
    region: str = "us-east-1"
    project_name: str = "stackvertex-project"
    terraform_version: str = ">= 1.0"

    def add_file(self, filename: str, content: str) -> None:
        """Fügt eine Datei zum Projekt hinzu.

        Args:
            filename: Dateiname (z.B. "main.tf")
            content: Dateiinhalt
        """
        self.files[filename] = content

    def write_to_directory(self, directory: Path) -> None:
        """Schreibt alle Dateien in ein Verzeichnis.

        Args:
            directory: Ziel-Verzeichnis
        """
        directory.mkdir(parents=True, exist_ok=True)

        for filename, content in self.files.items():
            file_path = directory / filename
            file_path.write_text(content, encoding="utf-8")
            logger.info(f"Written: {file_path}")

    def get_file_count(self) -> int:
        """Gibt Anzahl der Dateien zurück."""
        return len(self.files)

    def get_total_lines(self) -> int:
        """Gibt Gesamtzahl der Zeilen zurück."""
        return sum(content.count("\n") + 1 for content in self.files.values())


class TerraformFileBuilder:
    """Builder für Terraform-Datei-Struktur."""

    def __init__(self):
        """Initialisiert Builder."""
        self.resources: list[str] = []
        self.variables: list[dict[str, Any]] = []
        self.outputs: list[dict[str, Any]] = []
        self.locals: dict[str, Any] = {}

    def add_resource(self, hcl_code: str) -> None:
        """Fügt eine Resource hinzu.

        Args:
            hcl_code: HCL Code für Resource
        """
        self.resources.append(hcl_code)

    def add_variable(
        self,
        name: str,
        type_: str = "string",
        description: str = "",
        default: Any | None = None
    ) -> None:
        """Fügt eine Variable hinzu.

        Args:
            name: Variable Name
            type_: Variable Type (string, number, bool, list, map)
            description: Variable Description
            default: Default Value (optional)
        """
        variable = {
            "name": name,
            "type": type_,
            "description": description,
        }
        if default is not None:
            variable["default"] = default

        self.variables.append(variable)

    def add_output(
        self,
        name: str,
        value: str,
        description: str = "",
        sensitive: bool = False
    ) -> None:
        """Fügt einen Output hinzu.

        Args:
            name: Output Name
            value: Output Value (HCL expression)
            description: Output Description
            sensitive: Ob Output sensitive ist
        """
        self.outputs.append({
            "name": name,
            "value": value,
            "description": description,
            "sensitive": sensitive,
        })

    def add_local(self, name: str, value: Any) -> None:
        """Fügt eine Local Variable hinzu.

        Args:
            name: Local Variable Name
            value: Wert (wird zu HCL konvertiert)
        """
        self.locals[name] = value

    def build_provider_tf(
        self,
        provider: str,
        region: str,
        additional_config: dict[str, Any] | None = None
    ) -> str:
        """Generiert provider.tf Inhalt.

        Args:
            provider: Provider Name (z.B. "aws")
            region: Provider Region
            additional_config: Zusätzliche Provider-Config

        Returns:
            HCL Code für provider.tf
        """
        lines = [
            "# Provider Configuration",
            "# Generated by StackVertex",
            "",
            "terraform {",
            "  required_version = \">= 1.0\"",
            "",
            "  required_providers {",
            f"    {provider} = {{",
            "      source  = \"hashicorp/aws\"",
            "      version = \"~> 5.0\"",
            "    }",
            "  }",
            "}",
            "",
            f"provider \"{provider}\" {{",
            f"  region = \"{region}\"",
        ]

        # Additional config
        if additional_config:
            for key, value in additional_config.items():
                if isinstance(value, str):
                    lines.append(f"  {key} = \"{value}\"")
                else:
                    lines.append(f"  {key} = {value}")

        lines.append("}")
        lines.append("")

        return "\n".join(lines)

    def build_variables_tf(self) -> str:
        """Generiert variables.tf Inhalt.

        Returns:
            HCL Code für variables.tf
        """
        if not self.variables:
            return "# No variables defined\n"

        lines = [
            "# Variables",
            "# Generated by StackVertex",
            "",
        ]

        for var in self.variables:
            lines.append(f"variable \"{var['name']}\" {{")
            lines.append(f"  type        = {var['type']}")

            if var.get("description"):
                lines.append(f"  description = \"{var['description']}\"")

            if "default" in var:
                default_val = var["default"]
                if isinstance(default_val, str):
                    lines.append(f"  default     = \"{default_val}\"")
                elif isinstance(default_val, bool):
                    lines.append(f"  default     = {str(default_val).lower()}")
                else:
                    lines.append(f"  default     = {default_val}")

            lines.append("}")
            lines.append("")

        return "\n".join(lines)

    def build_outputs_tf(self) -> str:
        """Generiert outputs.tf Inhalt.

        Returns:
            HCL Code für outputs.tf
        """
        if not self.outputs:
            return "# No outputs defined\n"

        lines = [
            "# Outputs",
            "# Generated by StackVertex",
            "",
        ]

        for output in self.outputs:
            lines.append(f"output \"{output['name']}\" {{")
            lines.append(f"  value       = {output['value']}")

            if output.get("description"):
                lines.append(f"  description = \"{output['description']}\"")

            if output.get("sensitive"):
                lines.append("  sensitive   = true")

            lines.append("}")
            lines.append("")

        return "\n".join(lines)

    def build_main_tf(self) -> str:
        """Generiert main.tf Inhalt.

        Returns:
            HCL Code für main.tf
        """
        lines = [
            "# Main Resources",
            "# Generated by StackVertex",
            "",
        ]

        # Locals (if any)
        if self.locals:
            lines.append("locals {")
            for name, value in self.locals.items():
                if isinstance(value, str):
                    lines.append(f"  {name} = \"{value}\"")
                else:
                    lines.append(f"  {name} = {value}")
            lines.append("}")
            lines.append("")

        # Resources
        for resource_hcl in self.resources:
            lines.append(resource_hcl)
            lines.append("")

        return "\n".join(lines)

    def build_project(
        self,
        provider: str,
        region: str,
        project_name: str
    ) -> TerraformProject:
        """Baut komplettes Terraform-Projekt.

        Args:
            provider: Provider Name
            region: Region
            project_name: Projekt Name

        Returns:
            TerraformProject mit allen Dateien
        """
        project = TerraformProject(
            provider=provider,
            region=region,
            project_name=project_name
        )

        # Provider
        project.add_file("provider.tf", self.build_provider_tf(provider, region))

        # Variables
        if self.variables:
            project.add_file("variables.tf", self.build_variables_tf())

        # Main
        if self.resources or self.locals:
            project.add_file("main.tf", self.build_main_tf())

        # Outputs
        if self.outputs:
            project.add_file("outputs.tf", self.build_outputs_tf())

        return project
