"""Add terraform_state to deployments

Revision ID: 2af139d673c1
Revises: 8339d437ebd0
Create Date: 2026-04-18 19:42:53.368691

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af139d673c1'
down_revision: str | Sequence[str] | None = '8339d437ebd0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('terraform_state', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'terraform_state')
    # ### end Alembic commands ###
