"""Add CANCELLED status to deployments

Revision ID: 8339d437ebd0
Revises: 2bb8817606f8
Create Date: 2026-04-18 11:55:33.220926

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8339d437ebd0'
down_revision: str | Sequence[str] | None = '2bb8817606f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
