#!/bin/bash
set -euo pipefail

# StackVertex AWS Infrastructure Bootstrap Script
# This script sets up the Terraform state backend (S3 + DynamoDB)

echo "🚀 StackVertex AWS Infrastructure Bootstrap"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check prerequisites
echo "📋 Checking prerequisites..."

if ! command -v aws &> /dev/null; then
    echo -e "${RED}❌ AWS CLI not found. Please install: https://aws.amazon.com/cli/${NC}"
    exit 1
fi

if ! command -v terraform &> /dev/null; then
    echo -e "${RED}❌ Terraform not found. Please install: https://www.terraform.io/downloads${NC}"
    exit 1
fi

if ! command -v jq &> /dev/null; then
    echo -e "${YELLOW}⚠️  jq not found (optional but recommended)${NC}"
fi

echo -e "${GREEN}✅ Prerequisites OK${NC}"
echo ""

# Get AWS Account ID
echo "🔍 Detecting AWS Account..."
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>/dev/null || echo "")

if [ -z "$AWS_ACCOUNT_ID" ]; then
    echo -e "${RED}❌ Could not detect AWS Account. Please configure AWS CLI:${NC}"
    echo "   aws configure"
    exit 1
fi

echo -e "${GREEN}✅ AWS Account: $AWS_ACCOUNT_ID${NC}"
echo ""

# Get AWS Region (from config or ask)
AWS_REGION=$(aws configure get region 2>/dev/null || echo "eu-central-1")
echo "🌍 AWS Region: $AWS_REGION"
echo ""

# Confirm
echo -e "${YELLOW}📝 Configuration:${NC}"
echo "   Project: stackvertex"
echo "   AWS Account: $AWS_ACCOUNT_ID"
echo "   AWS Region: $AWS_REGION"
echo ""
read -p "Continue with bootstrap? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Bootstrap cancelled"
    exit 1
fi

# Navigate to bootstrap directory
cd "$(dirname "$0")/../terraform/bootstrap"

# Initialize Terraform
echo ""
echo "🔧 Initializing Terraform..."
terraform init

# Create terraform.tfvars
echo ""
echo "📝 Creating terraform.tfvars..."
cat > terraform.tfvars <<EOF
aws_account_id = "$AWS_ACCOUNT_ID"
aws_region     = "$AWS_REGION"
project_name   = "stackvertex"
EOF

# Plan
echo ""
echo "📊 Planning infrastructure..."
terraform plan -out=tfplan

# Confirm apply
echo ""
echo -e "${YELLOW}⚠️  This will create:${NC}"
echo "   - S3 bucket for Terraform state"
echo "   - DynamoDB table for state locking"
echo "   - S3 bucket for deployment states"
echo ""
read -p "Apply changes? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Bootstrap cancelled"
    rm -f tfplan
    exit 1
fi

# Apply
echo ""
echo "🚀 Creating infrastructure..."
terraform apply tfplan

# Get outputs
echo ""
echo "📤 Getting outputs..."
STATE_BUCKET=$(terraform output -raw terraform_state_bucket)
LOCKS_TABLE=$(terraform output -raw terraform_locks_table)
DEPLOYMENT_BUCKET=$(terraform output -raw deployment_states_bucket)

# Create backend config for environments
echo ""
echo "📝 Creating backend configurations..."

for ENV in dev staging prod; do
    BACKEND_FILE="../environments/$ENV/backend.tf"
    mkdir -p "../environments/$ENV"

    cat > "$BACKEND_FILE" <<EOF
# Terraform Backend Configuration
# Auto-generated by bootstrap script

terraform {
  backend "s3" {
    bucket         = "$STATE_BUCKET"
    key            = "environments/$ENV/terraform.tfstate"
    region         = "$AWS_REGION"
    encrypt        = true
    dynamodb_table = "$LOCKS_TABLE"
  }
}
EOF

    echo "   ✅ Created $BACKEND_FILE"
done

# Create .env file for backend
echo ""
echo "📝 Creating .env file for backend..."
cat > ../../../backend/.env.aws <<EOF
# AWS Configuration (Auto-generated by bootstrap)
AWS_REGION=$AWS_REGION
AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID

# Terraform State Storage
TERRAFORM_STATE_BUCKET=$STATE_BUCKET
DEPLOYMENT_STATE_BUCKET=$DEPLOYMENT_BUCKET

# Application Settings
DATABASE_URL=postgresql://\${DB_USER}:\${DB_PASSWORD}@\${DB_HOST}:5432/stackvertex
TERRAFORM_WORKSPACE_DIR=/tmp/stackvertex/deployments
EOF

echo "   ✅ Created backend/.env.aws"

# Summary
echo ""
echo -e "${GREEN}=========================================="
echo "✅ Bootstrap Complete!"
echo "==========================================${NC}"
echo ""
echo "📦 Created Resources:"
echo "   - State Bucket: $STATE_BUCKET"
echo "   - Locks Table: $LOCKS_TABLE"
echo "   - Deployment Bucket: $DEPLOYMENT_BUCKET"
echo ""
echo "📝 Next Steps:"
echo "   1. cd ../environments/dev"
echo "   2. terraform init"
echo "   3. terraform plan"
echo "   4. terraform apply"
echo ""
echo "📚 Documentation: docs/deployment/AWS_DEPLOYMENT.md"
echo ""
